approve_by_comment: true
approve_regex: '^([A|a]pproved|:\+1:|([L|l]ooks good[ to me]?))'
reject_regex: '^([R|r]ejected|:\-1:)'
reset_on_push: true
reviewers:
  name: approvers
  required: 2
  members:
      - xushWT
      - Henningstone
