static const char *apSayings[] = {
		"The client with the keck!"
		,"Project codename: D.I.C.K.E.R. D.E.N.N.I.S"
		,"KAT ZE! :3"
		,"You can keep bugs you find any!"
		,"Random splash!"
		,"LUABRIDGE!"
		,"Low on calories!"
		,"DENNIS!"
		,"KECK!"
		,"1338 - The Next Level"
		,"1338 - Off By One"
		,"1338 - Close Enough"
		,"1338 - Gone Too Far"
		,"1338 - One Step Ahead"
		,"1338 - Crossing Boarders"
		,"1338 - Eine Idee weiter"
		,"0x53A-0x539=0x1"
		,"Waiting for 0.7 (to die so this client remains usable)!"
		,"YAA, SPAß IM LEBEN!"
		,"Dennis * dennis = new Dennis()"
		,"Definitely legal!"
		,"Lua goes OOP!"
		,"SMOOTH!"
		,"This game was named 'Teewars'"
		,"long time ago..."
		,"Containing free melon-power!"
		,"Jump the gun!"
		,"øıŋĸ?"
		,"$$00QC$$0Q0o$$0QQl$$Q00o$$Q0Qr$$UM7m$$QQQa$$999t$$99Zi$$9Z9c"
		,"Have fun!"
		,"What is a floppy disk...?"
		,"Do you expect Haxx?"
		,"!!!!11eleven"
		,"Don't be salty!"
		,"This text is stored in static const char *s_apSayings[]"
		,"Rainbows are awesome"
		,"Blue is the color of life...!"
		,"Melons can be green, yellow or a hat!"
		,"Sublime!"
		,"Try toggle_hotbar!"
		,"Try toggle_irc!"
		,"- allthehaxx.github.io -"
		,"beta no more!"
		,"The crasher got removed :c"
		,"100+ commits per week!"
		,GAME_NETVERSION
		,"Built on " BUILD_DATE
		,"Version " ALLTHEHAXX_VERSION
		,"Searching for ideas..."
		,"(mooning) (sheep) (dog)"
		,".calc 2^10*5e3"
		,"Tequila!!! DODO DODODO DODO DO!"
		,"They will not force us!"
		,"Got many splashes, pfew"
		,"Seperated by a comma."
		,"::.. xx-xx-xx ..::"
		,"Do not count 'em ;)"
		,"Guaranteed to be 420% verkeckt!"
		,"CI Status: PASSED"
		,"rm -rf /"
		,"Markdown supported"
		,"You can click links!"
		,"Keep it up-to-date all the time"
		,"Join the chat!"
		,"No forum no more! ;)"
		,"It has to be teeish"
		,"Don't quote liars!"
		,"(4N Y0U R34D 7H15??"
		,"Going out of splash texts...."
		,"Life is strange :o"
		,"¿¡¿¡¿¡¿¡¿¡¿¡¿¡¿¡"
		,"...REISUB!"
		,"WO\xD0\xAFK\xC6\xA7 FO\xD0\xAF M\xC6\x8E"
		,"Do you get the insiders...? :D"
		,"Ask if you need something!"
		,"Brain.exe has stopped working"
		,"Read error: Could not access data at address 0x00000000"
		,"Do you play an instrument?"
		,"Cucumber ya mei lord, cucumber ya!"
		,"git rebase -i HEAD~~"
		,"Multicoloral!"
		,"Localize(\"%s\")"
		,"func = assert(load(\"return \" .. x))"
		,"RegisterEvent(\"OnIdle\", \"fap\")"
		,"Grr Java ate my brain"
		,"May contain traces of peanuts."
		,"It\x0A is\x0A  line\x0A   break\x0A    ing!"
		,"146 ist der Boss."
		,"Würselen city, boys!"
		,"Meet me at Internetcaffee 52146."
		,"Caitlyn Jenner is stunning and beautiful."
		,"Der Junge ist jetzt einer von uns."
		,"Chef's Chocolate Salty Balls"
		,"Fat Camp"
		,"Spoiler: Kenny dies!"
		,"There are more stars in the sky than there are atoms in the universe"
		,"\"Use the force, Harry!\" - Gandalf"
		,"\"Quotations on the internet are often attributed incorrectly.\" - Abraham Lincoln"
		,"\"Bitches ain't shit but hoes and tricks.\" - Ghandi"
		,"You miss 100% of the shots you don't take"
		,"Taking shots without bullets"
		,"I'm too drunk to taste this chicken."
		,"Panamera"
		,"Hercules Prima 5"
		,"Pirate on the weekend!"
		,"Why did the chicken cross the road?"
		,"Are you even trying?"
		,"What if everyone jumped at once?"
		,"What color is a mirror?"
		,"What if the moon was a disco ball?"
		,"Is your red the same red as my red?"
		,"Is anything real?"
		,"What is the speed of dark?"
		,"What is random?"
		,"Is the 5-second rule actually true?"
		,"How much does Thor's hammer weigh?"
		,"How much does a shadow weigh?"
		,"ReD go TW!!!"
		,"At least I got me for life"
		,"SIDEKICKS!"
		,"Drunk driving is okay if you buckle up."
		,"If you get kicked out of the bars just hit the boulevard."
		,"Flipping balisong..."
		,"Shoutout to my son Fruchti!"
		,"Random != Random"
		,"The smooth loading screen isn't threadsafe :("
		,"Shaders would be awesome!"
		,"SDL2 <3"
		,"8th May 2016 – 100 issues closed! (27 to go)"
		,"Computers don't byte!"
		,"git stash pop stash@{0}"
		,"Splashtexts for teh lulz ^^"
		,"Was he drunk...?"
		,"...no."
		,"What is a 'Neologism' ??"
		,"How could you know that?!"
		,"The spelling is 'whether', NOT 'wether'!!!"
		,"\"Zwei Russen sind besser als einer\""
		,"[20:49:00] Prinzessin Meskalin: ReD + 11 min = rip"
		,"[21:00:00] ReD: auutsch"
		,"\"Red nur du ReD\""
		,"BAUM!"
		,"epppiiiiccc"
		,"Gimme dat muzik!"
		,"...it's evolving!"
		,"When will the Aliens find us?"
		,"Gotta get more sleep :("
		,"We furfill every wish!"
		,"I hate fucking script kiddies"
		,"Don't be rude!"
		,"Nobody needs nothing"
		,"[IRC] received a CTCP FINGER"
		,"xoring you out!"
		,"Text formatting would be cool"
		,"Do penguins have knees?"
		,"Did you know: You can use CTRL+F in the consoles to search for text"
		,"Did you know: In the consoles, you can mark text to copy it"
		,"\"I'm in love with my lust, burning angel wings to dust!\""
		,"\"A square doesn't fit the circle\" ¯\\_(°-^)_/¯"
		,"The cake is a lie!"
		,"Happy tears fade fast, Sad tears tend to last"
		,"No, the cake is not a lie!"
		,"Tell me, Mechanist, is it true?"
		,"Remember: the Weighted Companion Cube cannot talk!"
		,"We are here to drink your beer!"
		,"If it ain't broken, break it!"
		,"The higher you will go, the deeper you can fall"
		,"Geistig stark gelähmt"
		,"Spilling the sauce since 2015"
		,"Not a bot client. No, for real this time."
		,"Medskalin Ô.Ô"
		,"Try Peyote cactus"
		,"xush' == Meskalin ô.O"
};