#ifndef GAME_CLIENT_COMPONENTS_MENUS_MANUAL__DEFINES_IMPL_H
#define GAME_CLIENT_COMPONENTS_MENUS_MANUAL__DEFINES_IMPL_H
#undef GAME_CLIENT_COMPONENTS_MENUS_MANUAL__DEFINES_IMPL_H // this file will be included multiple times

#undef PUTLINE
#undef NEWLINE

#endif